version: "3.8"

services:
  db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  # app:
  #   build:
  #     context: .
  #   ports:
  #     - "3000:3333"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql://docker:docker@db:5432/app
  #     - JWT_SECRET={JWT_SECRET}
  #     - env=production
  #   networks:
  #     - app_network

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
