name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  component-unit-test:
    name: "Component and Unit Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node | ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - run: npm ci
      - run: npm run test:coverage

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-node-${{ matrix.node }}
          path: ./coverage/
          if-no-files-found: warn

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"

  sast:
    name: "SAST Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        continue-on-error: true # Garante que erros não quebrem o pipeline

      - name: Create directory for SARIF report
        run: mkdir -p ./results

      - name: Export SAST Report
        run: |
          if [ -f ./results/results.sarif ]; then
            cp ./results/results.sarif sast-report.sarif
          else
            echo "No SARIF report generated" > sast-report.sarif
          fi

      - name: Upload SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: sast-report.sarif

  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    needs: [component-unit-test, e2e-tests]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and Push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: henriquelimadev/gc-sistematizacao:${-{ steps.generate_tag.outputs.sha }-},henriquelimadev/gc-sistematizacao:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: henriquelimadev/gc-sistematizacao:${{ steps.generate_tag.outputs.sha }},henriquelimadev/gc-sistematizacao:latest
          outputs: type=docker,dest=/tmp/gc-sistematizacao-image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gc-sistematizacao-docker-image
          path: /tmp/gc-sistematizacao-image.tar
          retention-days: 5

      - name: Push Docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: henriquelimadev/gc-sistematizacao:${{ steps.generate_tag.outputs.sha }},henriquelimadev/gc-sistematizacao:latest
